# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Eliza Weisman
url:              https://elizas.website
paginate:         1
baseurl:          /
author:
  name:           Eliza Weisman
  url:            https://elizas.website
  email:          hawk@hawkweisman.me

exclude: ["website.sublime-project", "website.sublime-workspace", "*.log", "*.fdb_latexmk", "*.synctex.gz", "*.aux"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: main"
  -
    scope:
      path: "notebook"
      type: "posts"
    values:
      layout: "post"
      author: "Eliza Weisman"

kramdown:
  input: GFM
