# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hawk Weisman
url:              https://hawkweisman.me
paginate:         1
baseurl:          /
author:
  name:           Hawk Weisman
  url:            https://hawkweisman.me
  email:          hawk@hawkweisman.me


kramdown:
  input: GFM