# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"

# Gems dependencies to be installed
gem "minima", "~> 2.5"
gem "webrick", "~> 1.7"
gem "github-pages", "~> 227", group: :jekyll_plugins

# Github Pages plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

